# Generated by Django 5.2.1 on 2025-05-08 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant_app', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='user',
        ),
        migrations.AddField(
            model_name='merchant',
            name='featured_dish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_by', to='dish_app.dish'),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='phone',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.CreateModel(
            name='MerchantLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('merchant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='login', to='merchant_app.merchant')),
            ],
        ),
        migrations.CreateModel(
            name='MerchantToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_token', to='merchant_app.merchantlogin')),
            ],
        ),
    ]
