# Generated by Django 5.0.6 on 2024-06-28 01:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("merchant_app", "0004_merchant_featured_dish"),
    ]

    operations = [
        migrations.AlterField(
            model_name="merchant",
            name="name",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="merchant",
            name="phone",
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
