# Generated by Django 5.0.6 on 2025-05-19 23:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics_app', '0001_create_analytics_views'),
        ('dish_app', '0005_alter_allergen_name_alter_dish_category_and_more'),
        ('user_app', '0004_user_date_of_birth_alter_user_gender_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishSalesView',
            fields=[
                ('dish', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='dish_app.dish')),
                ('total_sales', models.IntegerField()),
                ('online_sales', models.IntegerField()),
                ('offline_sales', models.IntegerField()),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('avg_rating', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'dish_sales_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MerchantSalesView',
            fields=[
                ('merchant_id', models.IntegerField(primary_key=True, serialize=False)),
                ('merchant_name', models.CharField(max_length=100)),
                ('total_orders', models.IntegerField()),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('avg_order_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('online_orders', models.IntegerField()),
                ('offline_orders', models.IntegerField()),
            ],
            options={
                'db_table': 'merchant_sales_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserActivityView',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('total_orders', models.IntegerField()),
                ('total_spent', models.DecimalField(decimal_places=2, max_digits=12)),
                ('avg_order_value', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('favorite_dishes_count', models.IntegerField()),
                ('reviews_count', models.IntegerField()),
            ],
            options={
                'db_table': 'user_activity_view',
                'managed': False,
            },
        ),
    ]
