# Generated by Django 5.0.6 on 2024-05-28 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish_app', '0002_initial'),
        ('merchant_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='merchant_app.merchant'),
        ),
    ]
