# Generated by Django 5.2.1 on 2025-05-08 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish_app', '0005_alter_allergen_name_alter_dish_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricehistory',
            options={},
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='changed_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-05-01 00:00:00'),
        ),
    ]
