# Generated by Django 5.2.1 on 2025-05-08 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dish_app', '0006_alter_pricehistory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricehistory',
            name='changed_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
