# Generated by Django 5.2.1 on 2025-05-08 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_dining_status',
            field=models.CharField(choices=[('dines_in', 'Dines In'), ('reservation', 'Reservation')], db_index=True, default='dines_in', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='is_reviewed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('preparing', 'Preparing'), ('completed', 'Completed')], db_index=True, max_length=10),
        ),
    ]
